site_name: 'UPPMAX: Singularity workshop'
repo_url: https://github.com/pmitev/UPPMAX-Singularity-workshop
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - How to install: installation.md
  - Building remotely: remote_builder.md
  - Building with --fakeroot: fakeroot.md
  - First steps:
    - 1.Running containrs from online repositories: remote_repositories.md
    - 2.Running Singularity container: running_singularity.md
    - 3.Building a container: build_container.md
    - 4.Something easy - exercise: exercise_00.md 
    - 5.Build own container - exercise: own_container.md
    - 6.Inspect containers: inspect.md
  - Additional:
    - Building interactively (sandbox): sandbox.md
    - NVIDIA Deep Learning Frameworks: PyTorch_NVIDIA.md  
    - Upload to Sylabs container library: exercise_02.md
  - Goods and bads: goods_bads.md
  - Reproducibility: reproducibility.md
  - Ubuntu template: ubuntu_template.md
  - Case Studies:
    - Portable BioTools: CaseStudies/portable_biotools.md
    - R.ROSETTA - R, wine, 32 bit: CaseStudies/R.ROSETTA.md
    - SLURM in container: CaseStudies/SLURM_in_container.md
    - Offline conda installer: CaseStudies/conda-offline.md
    - ORFfinder on Rackham: CaseStudies/ORFfinder.md
    - arcasHLA in Singularity: CaseStudies/arcasHLA.md
    - VESPA (conda, python2): CaseStudies/VESPA.md
    - gapseq enviroment: CaseStudies/gapseq.md
    - Jamovi Server: CaseStudies/jamovi.md
    - GitHub2Docker2Singularity: CaseStudies/github2docker2singularity.md
    - VSCode in Singularity: CaseStudies/VScode.md
    - MariaDB Server: CaseStudies/mariadb.md
    - FUSE overlayfs: CaseStudies/fuse-overlayfs.md
    - QEMU-utils: CaseStudies/qemu-utils.md
  - Advanced:
    - Singularity and MPI: mpi_applications.md
    - Gromacs in a container: mpi_gromacs.md
    - Singularity MPI@Kebnekaise: openmpi-benchmark.md
    - Convert Docker image to Singularity container: docker2singularity.md
    - Building from Singularity image: localimage.md
    - Multi-Stage Builds: multi-stage_builds.md
    - Indirect calls: indirect-call.md
  - UPPMAX in a can: uppmax_in_a_can.md
  - Practical information: practical_information.md
  - About: about.md
theme:
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  custom_dir: overrides
  features:
    - search.highlight
    - content.code.annotate
    - content.code.copy
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  - footnotes
  - attr_list
  - def_list
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
site_url: https://pmitev.github.io/UPPMAX-Singularity-workshop/
